import express from "express";
import Pharmacy from "../models/Pharmacy.model";
import Product from "../models/Product.model";
import PharmacyProduct from "../models/PharmacyProduct.model";

const router = express.Router();

/**
 * @route   POST /api/seed
 * @desc    Generate demo pharmacies, products, and relations for Dnipro, Ukraine
 */
router.post("/", async (req, res) => {
  try {
    await Pharmacy.deleteMany({});
    await Product.deleteMany({});
    await PharmacyProduct.deleteMany({});

    const pharmacies = await Pharmacy.insertMany([
      {
        name: "Аптека АНЦ",
        address: "просп. Дмитрия Яворницкого, 50",
        image: "https://encrypted-tbn0.gstatic.c=tbn:ANd9GcSXY-3fzJHk9HaRu3zahLHl_D4jYgpNPYVYsQ&s",
        coordinates: { lat: 48.464717, lng: 35.046183 },
        workingHours: {
          mon: { open: "08:00", close: "20:00" },
          tue: { open: "08:00", close: "20:00" },
          wed: { open: "08:00", close: "20:00" },
          thu: { open: "08:00", close: "20:00" },
          fri: { open: "08:00", close: "20:00" },
          sat: { open: "09:00", close: "18:00" },
          sun: { open: "09:00", close: "16:00" },
        },
      },
      {
        name: "Аптека Доброго дня",
        address: "просп. Героев, 12",
        image: "https://www.apteka.ua/wp/wp-content/uploads/2018/10/928395892351-1.jpg",
        coordinates: { lat: 48.425798, lng: 35.021785 },
        workingHours: {
          mon: { open: "08:00", close: "21:00" },
          tue: { open: "08:00", close: "21:00" },
          wed: { open: "08:00", close: "21:00" },
          thu: { open: "08:00", close: "21:00" },
          fri: { open: "08:00", close: "21:00" },
          sat: { open: "09:00", close: "19:00" },
          sun: { open: "09:00", close: "17:00" },
        },
      },
      {
        name: "Аптека 911",
        address: "ул. Паникахи, 2",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4xfVUaIdtSf3NOSpef96iF3vcI_rsybexhQ&s",
        coordinates: { lat: 48.464000, lng: 35.005000 },
        workingHours: {
          mon: { open: "09:00", close: "19:00" },
          tue: { open: "09:00", close: "19:00" },
          wed: { open: "09:00", close: "19:00" },
          thu: { open: "09:00", close: "19:00" },
          fri: { open: "09:00", close: "19:00" },
          sat: { open: "10:00", close: "17:00" },
          sun: { open: "10:00", close: "15:00" },
        },
      },
    ]);

    // 3. Создаём продукты (без expirationDate)
    const products = await Product.insertMany([
      {
        name: "Парацетамол",
        brand: "PharmaUA",
        description: "Жаропонижающее средство",
        category: "Жаропонижающее",
        prescriptionRequired: false,
      },
      {
        name: "Ибупрофен",
        brand: "HealthLife",
        description: "Обезболивающее и противовоспалительное",
        category: "Обезболивающее",
        prescriptionRequired: false,
      },
      {
        name: "Амоксиклав",
        brand: "Lek",
        description: "Антибиотик широкого спектра",
        category: "Антибиотики",
        prescriptionRequired: true,
      },
      {
        name: "Цитрамон",
        brand: "Darnitsa",
        description: "Обезболивающее средство",
        category: "Обезболивающее",
        prescriptionRequired: false,
      },
      {
        name: "Но-шпа",
        brand: "Sanofi",
        description: "Спазмолитик",
        category: "Спазмолитики",
        prescriptionRequired: false,
      },
      {
        name: "Лоратадин",
        brand: "Teva",
        description: "Противоаллергическое средство",
        category: "Антигистаминные",
        prescriptionRequired: false,
      },
      {
        name: "Аскорутин",
        brand: "Arterium",
        description: "Витаминный препарат",
        category: "Витамины",
        prescriptionRequired: false,
      },
      {
        name: "Корвалол",
        brand: "Фармак",
        description: "Седативное средство",
        category: "Седативные",
        prescriptionRequired: false,
      },
      {
        name: "Супрастин",
        brand: "EGIS",
        description: "Антигистаминное средство",
        category: "Антигистаминные",
        prescriptionRequired: false,
      },
      {
        name: "Фестал",
        brand: "Sanofi",
        description: "Ферментный препарат",
        category: "Ферменты",
        prescriptionRequired: false,
      },
      {
        name: "Мезим",
        brand: "Berlin-Chemie",
        description: "Ферментный препарат",
        category: "Ферменты",
        prescriptionRequired: false,
      },
      {
        name: "Активированный уголь",
        brand: "Дарница",
        description: "Сорбент",
        category: "Сорбенты",
        prescriptionRequired: false,
      },
      {
        name: "Смекта",
        brand: "Ipsen",
        description: "Сорбент",
        category: "Сорбенты",
        prescriptionRequired: false,
      },
      {
        name: "Регидрон",
        brand: "Orion",
        description: "Средство для регидратации",
        category: "Регидратация",
        prescriptionRequired: false,
      },
      {
        name: "Отипакс",
        brand: "Biocodex",
        description: "Капли ушные",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Називин",
        brand: "Merck",
        description: "Сосудосуживающие капли",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Граммидин",
        brand: "Валента",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Стрепсилс",
        brand: "Reckitt Benckiser",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Тантум Верде",
        brand: "Angelini",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Линекс",
        brand: "Sandoz",
        description: "Пробиотик",
        category: "Пробиотики",
        prescriptionRequired: false,
      },
      {
        name: "Бифидумбактерин",
        brand: "Partner",
        description: "Пробиотик",
        category: "Пробиотики",
        prescriptionRequired: false,
      },
      {
        name: "Энтерол",
        brand: "Biocodex",
        description: "Пробиотик",
        category: "Пробиотики",
        prescriptionRequired: false,
      },
      {
        name: "Дюфалак",
        brand: "Abbott",
        description: "Слабительное",
        category: "Слабительные",
        prescriptionRequired: false,
      },
      {
        name: "Гутталакс",
        brand: "Sanofi",
        description: "Слабительное",
        category: "Слабительные",
        prescriptionRequired: false,
      },
      {
        name: "Имодиум",
        brand: "Janssen",
        description: "Противодиарейное средство",
        category: "Противодиарейные",
        prescriptionRequired: false,
      },
      {
        name: "Лоперамид",
        brand: "Дарница",
        description: "Противодиарейное средство",
        category: "Противодиарейные",
        prescriptionRequired: false,
      },
      {
        name: "Флуконазол",
        brand: "Teva",
        description: "Противогрибковое средство",
        category: "Противогрибковые",
        prescriptionRequired: false,
      },
      {
        name: "Нистатин",
        brand: "Biosintez",
        description: "Противогрибковое средство",
        category: "Противогрибковые",
        prescriptionRequired: false,
      },
      {
        name: "Кетотифен",
        brand: "Sopharma",
        description: "Противоаллергическое средство",
        category: "Антигистаминные",
        prescriptionRequired: false,
      },
      {
        name: "Диклофенак",
        brand: "Teva",
        description: "Противовоспалительное средство",
        category: "Противовоспалительные",
        prescriptionRequired: false,
      },
      {
        name: "Нурофен",
        brand: "Reckitt Benckiser",
        description: "Обезболивающее и жаропонижающее",
        category: "Жаропонижающее",
        prescriptionRequired: false,
      },
      {
        name: "Пенталгин",
        brand: "Pharmstandard",
        description: "Комбинированное обезболивающее",
        category: "Обезболивающее",
        prescriptionRequired: false,
      },
      {
        name: "Анальгин",
        brand: "Дарница",
        description: "Обезболивающее средство",
        category: "Обезболивающее",
        prescriptionRequired: false,
      },
      {
        name: "Фервекс",
        brand: "UPSA",
        description: "Средство от простуды",
        category: "Простуда",
        prescriptionRequired: false,
      },
      {
        name: "Колдрекс",
        brand: "GlaxoSmithKline",
        description: "Средство от простуды",
        category: "Простуда",
        prescriptionRequired: false,
      },
      {
        name: "Терафлю",
        brand: "Novartis",
        description: "Средство от простуды",
        category: "Простуда",
        prescriptionRequired: false,
      },
      {
        name: "Арбидол",
        brand: "Pharmstandard",
        description: "Противовирусное средство",
        category: "Противовирусные",
        prescriptionRequired: false,
      },
      {
        name: "Анаферон",
        brand: "Материа Медика",
        description: "Противовирусное средство",
        category: "Противовирусные",
        prescriptionRequired: false,
      },
      {
        name: "Кагоцел",
        brand: "Nearmedic",
        description: "Противовирусное средство",
        category: "Противовирусные",
        prescriptionRequired: false,
      },
      {
        name: "Виферон",
        brand: "Ферон",
        description: "Иммуномодулятор",
        category: "Иммуномодуляторы",
        prescriptionRequired: false,
      },
      {
        name: "Иммунал",
        brand: "Sandoz",
        description: "Иммуномодулятор",
        category: "Иммуномодуляторы",
        prescriptionRequired: false,
      },
      {
        name: "Гриппферон",
        brand: "Фирн М",
        description: "Противовирусное средство",
        category: "Противовирусные",
        prescriptionRequired: false,
      },
      {
        name: "Синупрет",
        brand: "Bionorica",
        description: "Растительный препарат от простуды",
        category: "Простуда",
        prescriptionRequired: false,
      },
      {
        name: "Амбробене",
        brand: "Ratiopharm",
        description: "Отхаркивающее средство",
        category: "Отхаркивающие",
        prescriptionRequired: false,
      },
      {
        name: "Лазолван",
        brand: "Boehringer Ingelheim",
        description: "Отхаркивающее средство",
        category: "Отхаркивающие",
        prescriptionRequired: false,
      },
      {
        name: "Бромгексин",
        brand: "Berlin-Chemie",
        description: "Отхаркивающее средство",
        category: "Отхаркивающие",
        prescriptionRequired: false,
      },
      {
        name: "АЦЦ",
        brand: "Sandoz",
        description: "Муколитик",
        category: "Муколитики",
        prescriptionRequired: false,
      },
      {
        name: "Карбоцистеин",
        brand: "Sopharma",
        description: "Муколитик",
        category: "Муколитики",
        prescriptionRequired: false,
      },
      {
        name: "Синекод",
        brand: "Novartis",
        description: "Противокашлевое средство",
        category: "Противокашлевые",
        prescriptionRequired: false,
      },
      {
        name: "Геделикс",
        brand: "Krewel Meuselbach",
        description: "Растительный отхаркивающий препарат",
        category: "Отхаркивающие",
        prescriptionRequired: false,
      },
      {
        name: "Доктор Мом",
        brand: "Johnson & Johnson",
        description: "Растительный отхаркивающий препарат",
        category: "Отхаркивающие",
        prescriptionRequired: false,
      },
      {
        name: "Пектусин",
        brand: "Фармак",
        description: "Растительный отхаркивающий препарат",
        category: "Отхаркивающие",
        prescriptionRequired: false,
      },
      {
        name: "Трависил",
        brand: "Herbion",
        description: "Растительный отхаркивающий препарат",
        category: "Отхаркивающие",
        prescriptionRequired: false,
      },
      {
        name: "Эреспал",
        brand: "Servier",
        description: "Противовоспалительное средство",
        category: "Противовоспалительные",
        prescriptionRequired: false,
      },
      {
        name: "Флуимуцил",
        brand: "Zambon",
        description: "Муколитик",
        category: "Муколитики",
        prescriptionRequired: false,
      },
      {
        name: "Ренгалин",
        brand: "Materia Medica",
        description: "Противокашлевое средство",
        category: "Противокашлевые",
        prescriptionRequired: false,
      },
      {
        name: "Септолете",
        brand: "KRKA",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Фарингосепт",
        brand: "Терапия",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Гексорал",
        brand: "Johnson & Johnson",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Каметон",
        brand: "Фармстандарт",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
      {
        name: "Ингалипт",
        brand: "Дарница",
        description: "Антисептик для горла",
        category: "ЛОР",
        prescriptionRequired: false,
      },
    ]);

    const relations = [
      { pharmacy: pharmacies[0]._id, product: products[0]._id, price: 32, stock: 100, expirationDate: new Date("2026-12-31") },
      { pharmacy: pharmacies[0]._id, product: products[1]._id, price: 48, stock: 50, expirationDate: new Date("2025-10-10") },
      { pharmacy: pharmacies[0]._id, product: products[2]._id, price: 125, stock: 20, expirationDate: new Date("2025-05-15") },
      { pharmacy: pharmacies[0]._id, product: products[3]._id, price: 27, stock: 60, expirationDate: new Date("2026-07-01") },
      { pharmacy: pharmacies[0]._id, product: products[4]._id, price: 62, stock: 40, expirationDate: new Date("2026-03-15") },
      { pharmacy: pharmacies[0]._id, product: products[5]._id, price: 42, stock: 30, expirationDate: new Date("2027-01-01") },
      { pharmacy: pharmacies[0]._id, product: products[6]._id, price: 22, stock: 25, expirationDate: new Date("2027-05-10") },
      { pharmacy: pharmacies[0]._id, product: products[7]._id, price: 37, stock: 15, expirationDate: new Date("2026-11-11") },
      { pharmacy: pharmacies[0]._id, product: products[8]._id, price: 57, stock: 10, expirationDate: new Date("2026-09-09") },
      { pharmacy: pharmacies[0]._id, product: products[9]._id, price: 75, stock: 5, expirationDate: new Date("2027-02-02") },

      { pharmacy: pharmacies[1]._id, product: products[0]._id, price: 31, stock: 80, expirationDate: new Date("2026-12-31") },
      { pharmacy: pharmacies[1]._id, product: products[2]._id, price: 127, stock: 18, expirationDate: new Date("2025-05-15") },
      { pharmacy: pharmacies[1]._id, product: products[4]._id, price: 63, stock: 35, expirationDate: new Date("2026-03-15") },
      { pharmacy: pharmacies[1]._id, product: products[6]._id, price: 23, stock: 22, expirationDate: new Date("2027-05-10") },
      { pharmacy: pharmacies[1]._id, product: products[8]._id, price: 58, stock: 12, expirationDate: new Date("2026-09-09") },
      { pharmacy: pharmacies[1]._id, product: products[10]._id, price: 82, stock: 8, expirationDate: new Date("2027-03-03") },
      { pharmacy: pharmacies[1]._id, product: products[12]._id, price: 17, stock: 30, expirationDate: new Date("2028-01-01") },
      { pharmacy: pharmacies[1]._id, product: products[14]._id, price: 67, stock: 14, expirationDate: new Date("2027-12-12") },
      { pharmacy: pharmacies[1]._id, product: products[16]._id, price: 52, stock: 7, expirationDate: new Date("2026-06-06") },
      { pharmacy: pharmacies[1]._id, product: products[18]._id, price: 92, stock: 3, expirationDate: new Date("2026-10-10") },

      { pharmacy: pharmacies[2]._id, product: products[0]._id, price: 33, stock: 90, expirationDate: new Date("2026-12-31") },
      { pharmacy: pharmacies[2]._id, product: products[2]._id, price: 128, stock: 15, expirationDate: new Date("2025-05-15") },
      { pharmacy: pharmacies[2]._id, product: products[4]._id, price: 64, stock: 25, expirationDate: new Date("2026-03-15") },
      { pharmacy: pharmacies[2]._id, product: products[6]._id, price: 24, stock: 18, expirationDate: new Date("2027-05-10") },
      { pharmacy: pharmacies[2]._id, product: products[8]._id, price: 59, stock: 8, expirationDate: new Date("2026-09-09") },
      { pharmacy: pharmacies[2]._id, product: products[10]._id, price: 85, stock: 6, expirationDate: new Date("2027-03-03") },
      { pharmacy: pharmacies[2]._id, product: products[12]._id, price: 20, stock: 20, expirationDate: new Date("2028-01-01") },
      { pharmacy: pharmacies[2]._id, product: products[14]._id, price: 71, stock: 12, expirationDate: new Date("2027-12-12") },
      { pharmacy: pharmacies[2]._id, product: products[16]._id, price: 56, stock: 4, expirationDate: new Date("2026-06-06") },
      { pharmacy: pharmacies[2]._id, product: products[18]._id, price: 98, stock: 1, expirationDate: new Date("2026-10-10") },
    ];
    await PharmacyProduct.insertMany(relations);

    res.json({ message: "Данные успешно сгенерированы!" });
  } catch (err) {
    res.status(500).json({ message: "Ошибка сервера", error: err });
  }
});

export default router;